### ISSUE TITLE
[docs] Add a description of the browser’s localStorage for non-programmers

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo.io#106]
From today's discussion: [in the docs](https://mavo.io/docs/storage#local-storage), we use a JS-specific term `localStorage` that can be a bit hard to understand for non-programmers. It would be nice if we have an explanation of its meaning in simple words.

**Comment by code-reaper08** [comment]
## Hey @DmitrySharabin 👋 

I would like to take this issue.

Could you please assign it to me ?

Thanks in advance ❤️

**Comment by LeaVerou** [comment]
@code-reaper08 You don't need the issue assigned to you to submit a PR, and we don't tend to assign issues to people who have not contributed before unless they are officially working on Mavo in some capacity. If you want to work on it, just submit a PR, we're pretty informal around here! 😄

**Comment by code-reaper08** [comment]
> @code-reaper08 You don't need the issue assigned to you to submit a PR, and we don't tend to assign issues to people who have not contributed before unless they are officially working on Mavo in some capacity. If you want to work on it, just submit a PR, we're pretty informal around here! 😄 

Thanks for your quick reply @DmitrySharabin 😀👍

I will come with a PR soon 💯

**Comment by code-reaper08** [comment]
## Hello @LeaVerou ✌
I have a simple and conveying type of explanation for `localStorage` in my mind.

I have to edit **[this JSON](https://github.com/mavoweb/mavo.io/blob/7570419b24823b714eceaadf17cc557dfdab61ae/docs/docs.json)** file, am I right ?

**Comment by LeaVerou** [comment]
@code-reaper08 You can use Mavo to edit the page https://mavo.io/docs/storage and send a PR that way. To login to Mavo, add `?login` at the URL, since the toolbar is hidden.

@DmitrySharabin We should probably add an "Edit this page with Mavo" link at the bottom of pages, so that people don't need to know to add `?login` at the URL. See how it's done here: http://haystack.csail.mit.edu/

**Comment by code-reaper08** [comment]
> @code-reaper08 You can use Mavo to edit the page https://mavo.io/docs/storage and send a PR that way. To login to Mavo, add `?login` at the URL, since the toolbar is hidden.
> 
> @DmitrySharabin We should probably add an "Edit this page with Mavo" link at the bottom of pages, so that people don't need to know to add `?login` at the URL. See how it's done here: http://haystack.csail.mit.edu/

## Hello @LeaVerou 😄
I've added a short and conveying description for the term `localStorage` [here](https://mavo.io/docs/storage) using `?login` and created a PR [here](https://github.com/mavoweb/mavo.io/pull/113#issue-602109854).

Have a great day ✨

**Comment by DmitrySharabin** [comment]
The corresponding PR is already merged. So, we can close it.
