### ISSUE TITLE
Footer not aligned properly.

### ISSUE THREAD

**Issue by code-reaper08** [mavoweb/mavo.io#111]
Hello 😄
I noticed that the footer in the following links 
1. [https://mavo.io/docs/storage](https://mavo.io/docs/storage) 
2. [https://mavo.io/docs/primer](https://mavo.io/docs/primer)
3. [https://mavo.io/docs/properties](https://mavo.io/docs/properties)
4. [https://mavo.io/docs/collections](https://mavo.io/docs/collections) --> here links are accessible but not aligned well.
5. [https://mavo.io/docs/expressions](https://mavo.io/docs/expressions)
6. [https://mavo.io/docs/ui](https://mavo.io/docs/ui) --> here also links are accessible but not aligned well.
7. [https://mavo.io/docs/actions](https://mavo.io/docs/actions)
8. [https://mavo.io/docs/migration](https://mavo.io/docs/migration)
9. [https://mavo.io/docs/js](https://mavo.io/docs/js) --> here also links are accessible but not aligned well.

Are not aligned well,
so it hides and make the following links inaccessible,
- Get started
- Docs
- Demos
- FAQ
- Plugins

I noticed that it happens in full screen, When I resize the browser window, it aligns well.

## My Specs :

1. **OS** : Windows 10 (64-bit)

2. **Display size** : 1920 x 1080 

3. **Browsers tested** : Chrome Version 89.0.4389.90 and Firefox 87.0 (64-bit)

### **__Chrome__**

![mavofooterchrome](https://user-images.githubusercontent.com/64256342/112660243-39656500-8e7b-11eb-86d1-2265f8eb33e3.png)

### **__Firefox__**

![mavofooterfirefox](https://user-images.githubusercontent.com/64256342/112660258-3f5b4600-8e7b-11eb-82f8-cde53a479f6f.png)

**Comment by LeaVerou** [comment]
Thanks! We should probably tweak the media query so that the sidebar becomes inline earlier.

**Comment by DmitrySharabin** [comment]
Fixed by #136.
