### ISSUE TITLE
Horiontal Scrollbar does harm viewing experience

### ISSUE THREAD

**Issue by tapanchudasama** [mavoweb/mavo.io#127]
![image](https://user-images.githubusercontent.com/30605436/122636406-badd3400-d106-11eb-83a6-c2dbc2b94add.png)

I guess we should not display horizontal scrollbar and only show vertical scrollbar.

If this needs fix, I can do it.

**Comment by LeaVerou** [comment]
Hi there, I don't see a horizontal scrollbar in your screenshot?

**Comment by tapanchudasama** [comment]
Hey, I think the scrollbar was not visible in screenshot. 
I tried a different tool for screenshot this time. 
Visible this time.
![image](https://user-images.githubusercontent.com/30605436/122639991-9428f880-d11a-11eb-93da-cd3e3c414338.png)

**Comment by LeaVerou** [comment]
Which browser is this? What's the window size that a horizontal scrollbar starts being visible at?

**Comment by tapanchudasama** [comment]
This is Firefox running on Ubuntu. Window size is 1366x766.

**Comment by tapanchudasama** [comment]
Issue is with the `margin-left:21rem` which is applied to each section. 
If we could maybe reduce that, I think the scrollbar might go away. 
![Screenshot from 2021-06-19 23-49-12](https://user-images.githubusercontent.com/30605436/122651847-1afcc600-d159-11eb-9fa3-133eb3df7e90.png)

**Comment by LeaVerou** [comment]
That is needed for the scrollbar to not overlap with text though.

@DmitrySharabin do you want to take a quick look? It seems to be a Firefox-only issue across all platforms, for a small range of widths (so likely some media queries are a bit off)

**Comment by DmitrySharabin** [comment]
I also face this issue in Safari.

It looks like it's because of this media query:
https://github.com/mavoweb/mavo.io/blob/d7ad50f5516bb2f01c7c71158d737b4c5a8cd378/docs/style.scss#L194

<img width="1312" alt="Screen Shot 2021-06-22 at 16 50 24" src="https://user-images.githubusercontent.com/9166277/122937084-5a562d00-d37a-11eb-9a5b-44205628795b.png">
