### ISSUE TITLE
Get Mavo page

### ISSUE THREAD

**Issue by WraithKenny** [mavoweb/mavo.io#21]
Hello,

It seems the files on get.mavo.io, and which ones are given via https://mavo.io/get/ need to be audited. 

For example, the es5 versions (dev too) are missing the dependency files (like Bliss), which error out if used.

These should be bundled, or the head includes should list additional files.
(Edited)

**Comment by LeaVerou** [comment]
OMG, you're right, the es5 files don't include the dependencies. On it!
