### ISSUE TITLE
The github buttons at the plugin pages result in a 404

### ISSUE THREAD

**Issue by terabaud** [mavoweb/mavo.io#24]
When you click a GitHub button on a plugin page, you get a 404 Not Found error.

See, for example:
https://plugins.mavo.io/plugin/firebase

Am I getting it right there is a missing `mv-attribute="none"` attribute on the anchor tag? 
The buttons link to `https://github.com/[repo]` , `https://github.com/[repo]/issues` and `#` without substitution of the square bracket expressions.

**Comment by LeaVerou** [comment]
It looks like the buttons are created before expressions are picked up. Could be related to the new version of Github Buttons. Thanks for reporting this!

**Comment by LeaVerou** [comment]
This was fixed a while ago, I just forgot to close this issue!
