### ISSUE TITLE
Redirect to https

### ISSUE THREAD

**Issue by hkdobrev** [mavoweb/mavo.io#27]
Could you please redirect to https when the website is accessed through http? If possible, you could add an HSTS header as well. Thanks!

**Comment by LeaVerou** [comment]
I’m not a huge fan of forcing https, unless there's a reason. Is there a reason you need this?

**Comment by coliff** [comment]
HTTPS is fast becoming the standard way of serving all web traffic, why are you not a fan of it? There are many benefits:

- Google now rank HTTPS sites higher as they are more trustworthy (http://googlewebmastercentral.blogspot.com/2014/08/https-as-ranking-signal.html)
- Some third-party HTTPS sites do not allow referring links to non-HTTPS sites to be tracked in Google Analytics. Using HTTPS can give more accurate analytics data.
- ISPs like Verizon and Comcast are now routinely injecting tracking material into their customers traffic -- using HTTPS protects visitors from being manipulated in this way. Also some airport and hotel wi-fi services add tracking and even adverts in to websites – but it’s impossible to do that with sites served over HTTPS
- Sites served over HTTPS look safer and more professional with the nice green padlock icon in the top URL bar.
- A growing number of web technologies and APIs require HTTPS
- Web browsers (Chrome and Firefox) are beginning to show non-HTTPS sites as non-secure. so they will appear less trustworthy.

**Comment by hkdobrev** [comment]
Here is an article on how MITM attack could hijack your website even if you do redirect to HTTPS. Things like that are automatic and are placed on proxies, public WiFi and others if hacked. So not only you should be redirecting HTTP to HTTPS, but also HSTS header could help.

> I’m not a huge fan of forcing https

I don't see reasoning behind that.

**Comment by LeaVerou** [comment]
@coliff The benefits you list are benefits of HTTPS, which is already available. Not benefits for **forcing** HTTPS.

@karger thoughts?

**Comment by karger** [comment]
I don't see that it should be the job of a library to force https.  it 
would be odd for example if jquery silently rewrote every get as an 
https request.  also, if a user is foolish enough to http with github, 
they're probably using http elsewhere too, where we have no power to fix it.

**Comment by LeaVerou** [comment]
@karger they're talking about **our** website, mavo.io. This is the repo for the website, not the repo for Mavo :)

**Comment by karger** [comment]
my mistake.  I do think it's common (and good) practice for web sites to 
redirect to https.  Is there a standard mechanism that still permits 
serving http to browsers that (for who knows what reason) need http?

**Comment by LeaVerou** [comment]
We do redirect to https now, so I'm closing this.

**Comment by coliff** [comment]
There are some mixed content warnings on the site (insecure HTTP images being loaded on homepage) e.g.
http://julesmuck.com/wp-content/uploads/2016/04/mucklogoBLCK.png
http://data.mavo.io/portfolio/images/pasted-image-1494464667397.png
