### ISSUE TITLE
Misprints

### ISSUE THREAD

**Issue by AMurkin** [mavoweb/mavo.io#37]
Seems there are errors in Math column of [Functions with operators](https://mavo.io/docs/mavoscript/#functions-with-operators).
For lte row and eq row, probably.

**Comment by LeaVerou** [comment]
Thanks, fixed the `<=`. What issue do you see with the eq row?

**Comment by AMurkin** [comment]
If it's not supposed to put '==' there, then everything is fine.

**Comment by LeaVerou** [comment]
Nope, `=` works too! It's one of the differences of MavoScript vs JavaScript mentioned in the table below :)
