### ISSUE TITLE
typeof not in Primer

### ISSUE THREAD

**Issue by andreasplesch** [mavoweb/mavo.io#39]
https://mavo.io/docs/#core-attributes lists typeof and refers to the Primer but the Primer does not mention typeof. Perhaps linking to an example if there is one which uses typeof ?

**Comment by LeaVerou** [comment]
Oops, thanks!
I removed the link to Primer for now, but we really need to add proper documentation for `typeof` somewhere (and NOT in the Primer, as it's rarely needed)...
