### ISSUE TITLE
0.1.4 versions not found

### ISSUE THREAD

**Issue by valterkraemer** [mavoweb/mavo.io#40]
Mavo version 0.1.4 urls (e.g. https://get.mavo.io/0.1.4/mavo.es5.js) published on https://mavo.io/get/ does not work.

Is it btw possible to link to 0.1.5? Or do I have to host them myself if I don't want to use "latest stable version"?

**Comment by LeaVerou** [comment]
That's very weird, get.mavo.io is just the `dist/` directory, and only deploys on new releases.
As you can see both 0.1.5 and 0.1.4 are in there: https://github.com/mavoweb/mavo/tree/master/dist
I will investigate.

**Comment by LeaVerou** [comment]
Should be fixed now!
