### ISSUE TITLE
Sidebar menu overlapping with footnote links

### ISSUE THREAD

**Issue by nihal31** [mavoweb/mavo.io#50]
Link - https://mavo.io/docs/primer
Browser - Chrome v69.0.3497.92

![image](https://user-images.githubusercontent.com/4532171/46006491-4bf95a80-c0d5-11e8-8463-6241b71dd61f.png)

**Comment by LeaVerou** [comment]
Hey, thanks for filing an issue!

That's only when scrolled down at the bottom, when your resolution is not small enough for the small screen design to kick in, but is large enough that some of the text is under the sidebar. 

I don't consider it a bug exactly, it's just a suboptimal state of a fluid UI. However, I will apply `backdrop-filter: blur(5px);` to improve readability in this case. I will leave this open until that.
