### ISSUE TITLE
eshop demo is broken

### ISSUE THREAD

**Issue by JLuc** [mavoweb/mavo.io#57]
is it me or https://mavo.io/demos/eshop/ is broken ?

added-to-cart items are added as empty new entries at the bottom of the product list instead of going in the cart

Chromium 71.0.3578.98 (Build officiel) running on Ubuntu 18.04 (64 bits)

**Comment by LeaVerou** [comment]
I can confirm it is not just you. It was working recently, so I suspect a recent change broke it. Thanks so much for reporting!!

**Comment by LeaVerou** [comment]
Should be fixed now, thank you so much!!

**Comment by JLuc** [comment]
Great :+1: 
BTW i noticed some other demo didnt work 100% properly :
- https://mavo.io/demos/words/ (clicking words does nothing)
- https://mavo.io/demos/dice/ (added dots on top of dice are blanks ?)

Mavo looks great.

**Comment by LeaVerou** [comment]
Those should be fixed now too, thank you!!
