### ISSUE TITLE
Drop .name and .shortname from docs

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo.io#59]
I tested these features not only in codepen: I added the `lang="en"` attribute to the `<html>`, `<body>` and Mavo root elements. The result is the same as in this testcase: https://codepen.io/dsharabin/pen/MREQVy?editors=1100.

**Comment by LeaVerou** [comment]
Thanks! They'll need to be updated. This is now provided as a second argument (e.g. `month(foo, 'shortname')` and there are many more format strings accepted too.

**Comment by DmitrySharabin** [comment]
That's cool! Thank you. I think I should have a closer look at the source code. :)

**Comment by LeaVerou** [comment]
If you do, please send a PR to fix the docs!
You might even be able to do it via Mavo :)
